version: "3"

tasks:
  curlSpec:
    cmds:
      - curl -so service_types.json https://aiven-rest-aiven-public-axeo-test.avns.net/v1/service_types
  curlSpecSensitive:
    requires:
      vars:
        - AIVEN_TOKEN
        - AIVEN_PROJECT_NAME
    cmds:
      - >
        curl -so integration_types.json "https://aiven-rest-aiven-public-axeo-test.avns.net/v1/project/{{.AIVEN_PROJECT_NAME}}/integration_types" --header "Authorization: aivenv1 {{.AIVEN_TOKEN}}"
      - >
        curl -so integration_endpoint_types.json "https://aiven-rest-aiven-public-axeo-test.avns.net/v1/project/{{.AIVEN_PROJECT_NAME}}/integration_endpoint_types" --header "Authorization: aivenv1 {{.AIVEN_TOKEN}}"
    silent: false
          
  generate:
    cmds:
      - go run main.go service_types.json integration_types.json integration_endpoint_types.json
  run:
    cmds:
      - task: curlSpec
      - task: curlSpecSensitive
      - task: generate
  build:
    cmds:
      - go build
  test:
    cmds:
      - go test -v ./...
  curlDist:
    desc: During the development, the diff might change multiple times. Downloads files from main
    cmds:
      - for: [service_types, integration_types, integration_endpoint_types]
        cmd: "curl -so ./pkg/dist/{{.ITEM}}.yml https://raw.githubusercontent.com/aiven/go-api-schemas/refs/heads/main/pkg/dist/{{.ITEM}}.yml"
